### ISSUE TITLE
cloud-init user_data not interpolating variables

### ISSUE THREAD

**Issue by ramin** [scaleway/terraform-provider-scaleway#2659]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.9.2

### Affected Resource(s)

* scaleway_instance_server

### Terraform Configuration Files

```hcl
resource "scaleway_instance_server" "node" {
  name  = "test"
  type  = "PRO2-M"
  image = "ubuntu_jammy"

  root_volume {
    delete_on_termination = false
  }

  additional_volume_ids = [scaleway_instance_volume.server_volume.id]

  user_data = {
    foo = "bar"

    cloud-init = file("${path.module}/cloud-init.yml")
  }

  lifecycle {
    ignore_changes = [user_data]
  }
}
```

then for cloud-init.yml, eg:

```
#cloud-config
package_update: true
write_files:
  - path: /mnt/data/start.sh
    permissions: '0755'
    content: |
      '${foo}'

runcmd:  
  - /path/to/binary --flag '${foo}'

```

### Expected Behavior

I'd expect the variables to have been interpolated and injected with the variables defined in user_data

### Actual Behavior

Raw '${foo}' remains in output of commands or written files

### Steps to Reproduce

1. `terraform apply`

### References

* #0000
